In [145]:
# Import Dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [130]:
sonar_data = pd.read_csv("sonar_data.csv",header=None)
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0000,1.0000,2.0000,3.0000,4.0000,5.0000,6.0000,7.0000,8.0000,9.0000,...,51.0000,52.0000,53.0000,54.0000,55.0000,56.0000,57.0000,58.0000,59.0000,60
1,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,Rock
2,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,Rock
3,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,Rock
4,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,Rock

In [131]:
sonar_data.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,...,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000
mean,0.029024,0.043037,0.053192,0.067989,0.093981,0.127993,0.149872,0.167647,0.215429,0.250325,...,0.255226,0.257375,0.259462,0.264477,0.267619,0.271340,0.275725,0.280638,0.285415,0.288773
std,0.023024,0.074196,0.140637,0.209006,0.277083,0.343719,0.411253,0.482414,0.553799,0.622745,...,3.457482,3.526829,3.596181,3.665337,3.734622,3.803865,3.873064,3.942228,4.011399,4.080668
min,0.000000,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013200,0.016500,0.019000,0.024400,0.038400,0.067100,0.081200,0.080500,0.097300,0.111400,...,0.008500,0.007300,0.005100,0.005400,0.004200,0.004400,0.003700,0.003600,0.003700,0.003100
50%,0.022800,0.030800,0.034400,0.044100,0.063000,0.092200,0.108300,0.112300,0.152300,0.183800,...,0.014000,0.011500,0.009600,0.009300,0.007500,0.006900,0.006000,0.005800,0.006500,0.005300
75%,0.035300,0.048400,0.058700,0.068100,0.102600,0.134200,0.154300,0.170200,0.235300,0.269600,...,0.020900,0.016800,0.014900,0.014500,0.012100,0.010800,0.010500,0.010500,0.010400,0.008600
max,0.137100,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,...,50.000000,51.000000,52.000000,53.000000,54.000000,55.000000,56.000000,57.000000,58.000000,59.000000

In [132]:
sonar_data.shape

(209, 61)

In [134]:
sonar_data[60]

0        60
1      Rock
2      Rock
3      Rock
4      Rock
       ...
204    Mine
205    Mine
206    Mine
207    Mine
208    Mine
Name: 60, Length: 209, dtype: object

In [135]:
sonar_data[60].value_counts()

60
Mine    111
Rock     97
60        1
Name: count, dtype: int64

In [136]:
# Mean Values for Decision

sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
60,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,...,50.000000,51.000000,52.000000,53.000000,54.000000,55.000000,56.000000,57.000000,58.000000,59.000000
Mine,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
Rock,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [137]:
# Seperate Data and Labels

X = sonar_data.drop(columns=60,axis=1)
y = sonar_data[60]

In [138]:
print(X)

         0       1       2       3       4       5       6       7       8   \
0    0.0000  1.0000  2.0000  3.0000  4.0000  5.0000  6.0000  7.0000  8.0000
1    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
2    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
3    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
4    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
204  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
205  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
206  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
207  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
208  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...       50       51       52       53       54       55  \
0    9.0000  ...  50.0000  51.0000  52.0000  53.0000  54.0000  55.0000
1    0.2111  ...   0.0232   0.0027   0.0065   0.0159   0.0072   0.0167
2    0.2872  ...   0.0125   0.0084   0.0089   0.0048   0.0094   0.0191
3    0.6194  ...   0.0033   0.0232   0.0166   0.0095   0.0180   0.0244
4    0.1264  ...   0.0241   0.0121   0.0036   0.0150   0.0085   0.0073
..      ...  ...      ...      ...      ...      ...      ...      ...
204  0.2684  ...   0.0203   0.0116   0.0098   0.0199   0.0033   0.0101
205  0.2154  ...   0.0051   0.0061   0.0093   0.0135   0.0063   0.0063
206  0.2529  ...   0.0155   0.0160   0.0029   0.0051   0.0062   0.0089
207  0.2354  ...   0.0042   0.0086   0.0046   0.0126   0.0036   0.0035
208  0.2354  ...   0.0181   0.0146   0.0129   0.0047   0.0039   0.0061

          56       57       58       59
0    56.0000  57.0000  58.0000  59.0000
1     0.0180   0.0084   0.0090   0.0032
2     0.0140   0.0049   0.0052   0.0044
3     0.0316   0.0164   0.0095   0.0078
4     0.0050   0.0044   0.0040   0.0117
..       ...      ...      ...      ...
204   0.0065   0.0115   0.0193   0.0157
205   0.0034   0.0032   0.0062   0.0067
206   0.0140   0.0138   0.0077   0.0031
207   0.0034   0.0079   0.0036   0.0048
208   0.0040   0.0036   0.0061   0.0115

[209 rows x 60 columns]

In [139]:
print(y)

0        60
1      Rock
2      Rock
3      Rock
4      Rock
       ...
204    Mine
205    Mine
206    Mine
207    Mine
208    Mine
Name: 60, Length: 209, dtype: object

In [118]:
# Training and Test Data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=1)

In [141]:
print(X_train)

          0       1       2       3       4       5       6       7       8  \
115  0.0414  0.0436  0.0447  0.0844  0.0419  0.1215  0.2002  0.1516  0.0818
38   0.0123  0.0022  0.0196  0.0206  0.0180  0.0492  0.0033  0.0398  0.0791
56   0.0152  0.0102  0.0113  0.0263  0.0097  0.0391  0.0857  0.0915  0.0949
123  0.0270  0.0163  0.0341  0.0247  0.0822  0.1256  0.1323  0.1584  0.2017
18   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
140  0.0412  0.1135  0.0518  0.0232  0.0646  0.1124  0.1787  0.2407  0.2682
5    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105
154  0.0117  0.0069  0.0279  0.0583  0.0915  0.1267  0.1577  0.1927  0.2361
131  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328

          9  ...      50      51      52      53      54      55      56  \
115  0.1975  ...  0.0222  0.0045  0.0136  0.0113  0.0053  0.0165  0.0141
38   0.0475  ...  0.0149  0.0125  0.0134  0.0026  0.0038  0.0018  0.0113
56   0.1504  ...  0.0048  0.0049  0.0041  0.0036  0.0013  0.0046  0.0037
123  0.2122  ...  0.0197  0.0189  0.0204  0.0085  0.0043  0.0092  0.0138
18   0.1520  ...  0.0045  0.0084  0.0010  0.0018  0.0068  0.0039  0.0120
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
140  0.2058  ...  0.0798  0.0376  0.0143  0.0272  0.0127  0.0166  0.0095
5    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057
154  0.2169  ...  0.0039  0.0053  0.0029  0.0020  0.0013  0.0029  0.0020
131  0.5378  ...  0.0228  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065

         57      58      59
115  0.0077  0.0246  0.0198
38   0.0058  0.0047  0.0071
56   0.0011  0.0034  0.0033
123  0.0094  0.0105  0.0093
18   0.0132  0.0070  0.0088
..      ...     ...     ...
140  0.0225  0.0098  0.0085
5    0.0027  0.0051  0.0062
154  0.0062  0.0026  0.0052
131  0.0141  0.0068  0.0086
203  0.0115  0.0193  0.0157

[187 rows x 60 columns]

In [119]:
# Logistic Regression Model Training

model = LogisticRegression()

In [120]:
model.fit(X_train, y_train)

LogisticRegression()

In [121]:
# Model Evaluation

#accuracy of training data
X_train_prediction = model.predict(X_train)
training_model_accuracy = accuracy_score(X_train_prediction, y_train)

In [122]:
print("Accuracy of the Training data :{}".format(training_model_accuracy))

Accuracy of the Training data :0.8342245989304813

In [123]:
#accuracy of test data
X_test_prediction = model.predict(X_test)
test_model_accuracy = accuracy_score(X_test_prediction, y_test)

print("Accuracy of the Test data :{}".format(test_model_accuracy))

Accuracy of the Test data :0.7619047619047619

In [142]:
input_data = (0.02,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.066,0.2273,0.31,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.555,0.6711,0.6415,0.7104,0.808,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.051,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.018,0.0084,0.009,0.0032)

input_data_as_numpy_array = np.asarray(input_data)

In [143]:
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

['Rock']

C:\Users\chauh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [127]:
if(prediction=='Rock'):
    print("Object is a Rock")
elif(prediction=='Mine'):
    print("Object is a Mine :(")
else:
    print("Error")

Object is a Mine :(